/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AdductBlacklist {
  active: Generated<boolean>;
  adduct_id: number;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  reason: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Adducts {
  charge: number;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: Generated<number>;
  ion_mode: string;
  label: string;
  mass_multiplier: Generated<number>;
  mass_shift: number;
  updated_at: Generated<Timestamp>;
}

export interface CompoundAdducts {
  adduct_id: number;
  compound_id: number;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  theoretical_mz: number;
}

export interface Compounds {
  accession: string;
  average_molecular_weight: number | null;
  chemical_formula: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  import_batch_id: number | null;
  iupac_name: string | null;
  monoisotopic_molecular_weight: number | null;
  name: string;
  sources_hierarchy: Json | null;
  traditional_iupac: string | null;
}

export interface CompoundSources {
  compound_id: number;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  level: number;
  parent_source_term_id: number | null;
  source_term_id: number;
}

export interface ImportBatches {
  created_at: Generated<Timestamp>;
  dataset_name: string;
  hmdb_release_date: Timestamp | null;
  id: Generated<number>;
  imported_at: Generated<Timestamp>;
  notes: string | null;
  source_filename: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface SourceTerms {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
}

export interface Spectra {
  collision_energy_voltage: number | null;
  compound_id: number;
  created_at: Generated<Timestamp>;
  hmdb_spectrum_id: number;
  id: Generated<number>;
  import_batch_id: number | null;
  instrument_type: string | null;
  ionization_mode: string | null;
  peak_counter: number | null;
  polarity: string | null;
  predicted: boolean;
  raw_metadata: Json | null;
  splash_key: string | null;
}

export interface SpectrumPeaks {
  created_at: Generated<Timestamp>;
  hmdb_msms_id: number | null;
  hmdb_peak_id: number | null;
  id: Generated<Int8>;
  mass_charge: number;
  normalized_intensity: number | null;
  raw_intensity: number | null;
  spectrum_id: number;
}

export interface DB {
  adduct_blacklist: AdductBlacklist;
  adducts: Adducts;
  compound_adducts: CompoundAdducts;
  compound_sources: CompoundSources;
  compounds: Compounds;
  import_batches: ImportBatches;
  source_terms: SourceTerms;
  spectra: Spectra;
  spectrum_peaks: SpectrumPeaks;
}
